# Generated by Django 5.2.5 on 2025-12-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
